name: Publish document

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Document
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish PDF Document
        run: |
          sudo apt-get install pandoc
          sudo "March 2022"/generate_standalone.cmd
      - name: Upload Document
        uses: actions/upload-artifact@v2
        id: upload-document
        with:
          name: 'March 2022.pdf'
          path: ${{ steps.publish-document.outputs.pdf }}
